// ── Structure board ─────────────────────────────────────────────────────────
// Regenerated by tools/structure.py (see .github/workflows/structure-board.yml).
// The rows below are the HAND-SEEDED starting board — each carries
// `seeded: true` — and the first bot run replaces them wholesale. Once that has
// happened, do not hand-edit this file: change the extractor instead.
//
// A SEPARATE element from the STOCKS cards in data.js. The same ticker may
// appear in both, and they are ALLOWED TO DISAGREE: a card carries a traded
// plan (entry, stop, rank, a thesis), this board carries structure (where
// demand and supply sit, what triggers which way). Neither overwrites the
// other, and nothing here is derived from data.js.
//
// The generated rows compute every field from one OHLC source per the written
// methodology: ATR(14) Wilder, confirmed swings (2 candles each side),
// displacement-formed zones with wick/body boundaries, revisit-and-acceptance
// strength grading, and the bias score
//     Score = 2W + D + 0.5H + 0.5R + 0.5M + 0.5O + Z
// with `parts` carrying each term so a bias on screen can be checked against
// its own inputs.
//
// The seeded rows below predate that score — the original board's bias was
// discretionary, so `score` and `parts` are null and `bias` holds the written
// verdict. A null score renders as "—", never as 0: an unscored row must not
// look like a neutral one.
//
// Row shape (generated):
//   ticker · date · price · atr · atrPct
//   structure { w, d, h4, h4Note }   — bullish | bearish | neutral per frame
//   ind       { rsi, macdHist, obvSlope }
//   parts     { W, D, H, R, M, O, Z } each −1 | 0 | +1
//   score · bias
//   demand[] / supply[]  { lo, hi, strength, touches, closesIn, since }
//   position · bull · bear · retest
// Seeded rows add: h4, h4Effect (the 4H read, prose) and note.
// Emphasis is **markdown bold** — script.js escapes each field as text first
// and only then turns `**…**` into <b>, so no raw HTML is ever injected.
const BOARD = {
    updated: '2026-08-01',
    generatedBy: 'hand-seeded — awaiting the first tools/structure.py run',
    method: 'Score = 2W + D + 0.5H + 0.5R + 0.5M + 0.5O + Z '
        + '(W weekly, D daily, H 4H structure; R RSI vs 50; M MACD histogram slope; '
        + 'O OBV slope; Z inside confirmed demand +1 / supply −1). '
        + 'Not yet applied to the seeded rows — their bias is the original discretionary read.',
    note: 'Structure only — where demand and supply sit and what triggers which way. '
        + 'Independent of the traded plans on the cards; the two are allowed to disagree.',
    // The 4H pass, most actionable first. Rendered under the table.
    ranking: [
        '**LITE short** — strongest alignment across weekly, daily and 4H.',
        '**STX short** — needs $842 and preferably $818 to fail.',
        '**AKAM rejection short** — if it remains below $118 and loses $112.',
        '**AXON long** — only after a confirmed $535–545 breakout.',
        '**TE long** — weakest confirmation; demand reacted, but the 4H rebound is already fading.',
    ],
    rankingNote: 'The biggest update is TE: it remains a possible countertrend long, '
        + 'but the 4H chart says wait, not buy yet.',
    // Direction ranking — which side each name is a candidate for, and on what
    // terms. A ticker can appear in more than one group on purpose: META, SMH
    // and CIEN are corrections inside larger monthly uptrends AND countertrend
    // bounce candidates, which are two true statements about the same chart.
    // This is the single source of truth — each row's membership label is
    // derived from these lists at render time, never restated per row.
    direction: {
        groups: [
            { label: 'Best trend-following longs', side: 'long',
              tickers: ['LLY', 'AVGO'] },
            { label: 'Possible longs after breakout confirmation', side: 'long',
              tickers: ['AXON', 'STX', 'MSFT'],
              note: 'AXON first, then STX. MSFT is long-first but its weekly '
                  + 'trend has only just turned, so it joins on either a $482 '
                  + 'breakout-retest or a pullback with a 4H higher low.' },
            { label: 'Best trend-following shorts', side: 'short',
              tickers: ['LITE', 'CRWV', 'INTC', 'AKAM'] },
            { label: 'Bearish corrections inside larger monthly uptrends', side: 'short',
              tickers: ['SMH', 'META', 'CIEN'] },
            { label: 'Countertrend bounce candidates only', side: 'long',
              tickers: ['TE', 'META', 'SMH', 'CIEN'] },
        ],
        note: 'The biggest correction to the earlier board is **TE**: being oversold '
            + 'inside demand makes a bounce possible, but its weekly, daily and 4H '
            + 'trends all remain down. The long is therefore **countertrend** and needs '
            + 'stronger confirmation than a normal trend-following long.',
    },
    // `price` on a seeded row is IMPLIED from its own ATR pair (atr / atrPct *
    // 100). That is not a guess: for every ticker that also has a card, the
    // implied price lands within 0.07% of our own close — so these ATR figures
    // and our OHLC are on the same basis.
    rows: [
        {
            // Weekly is 'bullish breakout/transition; NOT yet a confirmed
            // HH-HL uptrend' — so the enum is NEUTRAL, not bullish. One large
            // displacement candle is not a higher-high-and-higher-low
            // sequence, which is the same distinction classify_structure
            // enforces: a break needs a confirmed pivot behind it, and this
            // one has not made its higher low yet.
            //
            // Price is the stated $464.72 close; the ATR pair implies $464.35,
            // a 0.08% reconciliation. The read explicitly EXCLUDES a second
            // feed showing a materially lower ATR rather than averaging the
            // two — mixing methodologies is what made the earlier board's ATRs
            // inconsistent, so a single basis is kept here too.
            ticker: 'MSFT', seeded: true, date: '2026-08-02',
            price: 464.72, atr: 16.02, atrPct: 3.45,
            structure: { m: 'bullish', w: 'neutral', d: 'bullish', h4: 'bullish',
                         h4Note: 'read from charts' },
            trendProse: { m: 'long-term uptrend, recovering below prior high',
                          w: 'bullish breakout/transition — not yet a confirmed HH-HL uptrend',
                          d: 'strong bullish breakout, extended',
                          h4: 'uptrend, but stretched after the gap' },
            preferred: '**Long preferred.** Do not chase the two-day expansion; prioritise a pullback or a confirmed breakout-retest.',
            score: null, parts: null,
            bias: '**Long-first, but the weekly trend has only just turned.** The earnings gap is genuine bullish displacement; one large candle is not a completed higher-high/higher-low sequence.',
            h4: 'Uptrend but stretched: at $465 price sits roughly THREE ATRs above the pre-earnings area, so the attractive long is not simply buying here.',
            demand: [
                { lo: 449, hi: 451, strength: 'fresh', note: 'immediate' },
                { lo: 432, hi: 438, strength: 'fresh', note: 'earnings-gap support' },
                { lo: 419, hi: 423, strength: 'tested', note: 'major breakout shelf' },
                { lo: 389, hi: 400, strength: 'tested', note: 'lower gap base' },
            ],
            supply: [
                { lo: 466, hi: 482, strength: 'tested', note: 'immediate' },
                { lo: 500, hi: 505, strength: 'tested', note: 'next' },
                { lo: 537, hi: 550, strength: 'fresh', note: 'major supply / prior high' },
            ],
            position: 'About **three ATRs** above the pre-earnings area after a two-day expansion — extended, directly under immediate supply',
            bull: 'Close above **$482**, hold the retest of $466–482 → **$500–505**, then **$537–550**',
            longSetup: '**Breakout:** close above **$482**, then hold/retest $466–482 → **$500–505**, then **$537–550**. **Pullback:** defend $432–438 or $419–423, form a 4H higher low and reclaim the zone → **$466–482**',
            longCandidate: 'Long-first, but wait: either a pullback into **$449–451** or **$432–438** with a 4H higher low, or a **$482** break with a successful retest.',
            bear: 'Loss of **$432** → **$419–423**',
            shortSetup: 'Loss of **$432** → $419–423. A short only becomes structurally clean after a close below **$419** and a failed reclaim → **$400–389**',
            retest: 'First likely retest **$449–451**; a deeper gap retest could reach **$432–438**',
        },
        {
            ticker: 'LITE', seeded: true, date: '2026-08-01',
            price: 713.62, atr: 76, atrPct: 10.65,
            structure: { m: 'neutral', w: 'bearish', d: 'bearish', h4: 'bearish',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'parabolic trend breaking', w: 'downtrend',
                          d: 'downtrend', h4: 'failed relief bounce' },
            preferred: '**Strong short preference**',
            longSetup: 'Countertrend only above **$750** → $801–835',
            shortSetup: 'Weak bounce into **$719–750**, or loss of $700 → $681–662, then $620–575',
            score: null, parts: null,
            bias: '**Strongly bearish.** Continuation short preferred.',
            h4: 'Clear bearish structure: price below the $748, $781 and $813 averages. The rebound has rolled over near resistance.',
            h4Effect: 'Confirms LITE as the **strongest bearish setup**. Short a failed reclaim of **$719–735**, or a breakdown below **$674**. Targets: $620–590, then approximately $575. Do not chase while price is already sitting near its lower band.',
            demand: [
                { lo: 700, hi: 703, strength: 'tested', note: 'control' },
                { lo: 662, hi: 681, strength: 'tested', note: 'support' },
                { lo: 575, hi: 620, strength: 'weak', note: 'tested/weak demand' },
            ],
            supply: [
                { lo: 735, hi: 750, strength: 'tested', note: 'resistance' },
                { lo: 801, hi: 835, strength: 'fresh', note: 'main supply' },
            ],
            position: 'Near monthly control after heavy selling',
            bull: 'Strong close above **$750** → **$801–835**',
            bear: 'Weak green close below $750, then break of its low; or loss of **$700** → **$680–662**, **$611–595**, then **$575**',
            longCandidate: 'Currently the **weakest** long candidate — better to wait for confirmed demand around **$575–620** or a major structural reclaim.',
            retest: 'Breakdown may retest **$700–703** from underneath',
        },
        {
            // Monthly is 'limited history' — CRWV's listing is too young for a
            // 24-bar monthly lookback, so the frame is null rather than a guess.
            // The extractor reaches the same conclusion on its own: _frame_ok()
            // refuses to read a frame short of its lookback + ATR warmup.
            ticker: 'CRWV', seeded: true, date: '2026-08-01',
            price: 71.72, atr: 7.1, atrPct: 9.9,
            structure: { m: null, w: 'bearish', d: 'bearish', h4: 'bearish',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'insufficient history', w: 'downtrend',
                          d: 'downtrend', h4: 'downtrend' },
            preferred: '**Short preferred**',
            longSetup: 'Countertrend only after $60–65 holds and **$80** is reclaimed',
            shortSetup: 'Reject $74–80 or lose **$60** → $49–52',
            score: null, parts: null,
            bias: '**Strongly bearish with bounce risk.** Prefer rejection short from supply rather than chasing near demand.',
            h4: 'Relief bounce is failing — price is back under the 4H resistance and moving averages.',
            demand: [
                { lo: 60, hi: 65, strength: 'tested', note: 'major' },
                { lo: 49, hi: 52, strength: 'fresh', note: 'lower demand' },
            ],
            supply: [
                { lo: 74, hi: 80, strength: 'tested', note: 'immediate' },
                { lo: 86, hi: 97, strength: 'tested', note: 'main' },
                { lo: 106, hi: 125, strength: 'fresh', note: 'higher' },
            ],
            position: 'Below 4H resistance and moving averages, but only about one ATR above major demand',
            bull: 'Defend $60–65, form higher low and reclaim **$79–80** → **$86–90**, then **$96–100**',
            bear: 'Reject **$74–80** and lose $69–70 → **$65–60**; close below $60 and fail reclaim → **$49–52**',
            longCandidate: 'Long only after **$60–65** holds and **$74–80** is reclaimed.',
            retest: 'Breakdown below $60 may retest **$60–65** from underneath; reclaim above $80 may retest **$74–80** as support',
        },
        {
            // `structure` is a three-value enum (bullish | bearish | neutral),
            // so hedged prose maps to the CONSERVATIVE value and the full
            // wording is kept in `bias`: "neutral-to-bullish" weekly, "daily
            // balancing" and "4H compressed" are all neutral here — none is a
            // confirmed higher-high-and-higher-low read.
            ticker: 'AVGO', seeded: true, date: '2026-08-01',
            price: 388.97, atr: 16.57, atrPct: 4.26,
            structure: { m: 'bullish', w: 'bullish', d: 'neutral', h4: 'neutral',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend', w: 'uptrend/consolidation',
                          d: 'range', h4: 'compressed range' },
            preferred: '**Long preferred**',
            longSetup: 'Hold $378–383 and reclaim **$396–405** → $419–425, then $450–466',
            shortSetup: 'Short only after loss and failed reclaim of **$378** → $369–357',
            score: null, parts: null,
            bias: '**Neutral-to-bullish.** Prefer pullback hold or confirmed breakout long; short only after support failure.',
            h4: 'Compressed — coiling under the $382–390 moving-average cluster rather than trending.',
            demand: [
                { lo: 378, hi: 383, strength: 'tested', note: 'immediate' },
                { lo: 357, hi: 369, strength: 'tested', note: 'stronger' },
                { lo: 345, hi: 350, strength: 'fresh', note: 'secondary' },
            ],
            supply: [
                { lo: 396, hi: 405, strength: 'tested', note: 'immediate' },
                { lo: 419, hi: 425, strength: 'fresh', note: 'breakout zone' },
                { lo: 450, hi: 466, strength: 'fresh', note: 'major' },
            ],
            position: 'Trapped around the $382–390 moving-average cluster, directly below resistance',
            bull: 'Hold $378–383 and reclaim **$405** → **$419–425**, then **$450–466**',
            bear: 'Reject $396–405 and lose **$378** → **$369–357**; below $357 → **$345–350**',
            longCandidate: 'Trend-following long if **$378–383** holds and price reclaims **$396–405**.',
            retest: 'Breakout above $405 may retest **$396–405**; breakdown below $378 may retest **$378–383** from underneath',
        },
        {
            // ATR is explicitly PENDING on this read, so atr/atrPct stay null —
            // and with no ATR pair there is nothing to imply a price from, so
            // that is null too rather than borrowed from META's card. The first
            // bot run fills all three; the levels below stand on their own.
            ticker: 'META', seeded: true, date: '2026-08-01',
            price: 557.08, atr: 25.18, atrPct: 4.52,
            structure: { m: 'bullish', w: 'bearish', d: 'bearish', h4: 'bearish',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend under pressure', w: 'downtrend',
                          d: 'downtrend', h4: 'bearish rebound attempt' },
            preferred: '**Short trend; long only countertrend**',
            longSetup: 'Hold $520–545, form higher low and reclaim **$575–590** → $599–635',
            shortSetup: 'Reject $575–610, or lose **$520** → $500–490, then $470–450',
            score: null, parts: null,
            bias: '**Bearish correction with countertrend bounce potential.** Long only after confirmation from demand; rejection short is cleaner from higher prices.',
            h4: 'Attempting a rebound — an attempt, not yet a turn, so the 4H frame is read neutral rather than bullish.',
            demand: [
                { lo: 520, hi: 545, strength: 'tested', note: 'immediate' },
                { lo: 490, hi: 505, strength: 'tested', note: 'secondary' },
                { lo: 450, hi: 470, strength: 'fresh', note: 'lower demand' },
            ],
            supply: [
                { lo: 575, hi: 590, strength: 'tested', note: 'first' },
                { lo: 599, hi: 610, strength: 'tested', note: 'main' },
                { lo: 625, hi: 635, strength: 'fresh', note: 'major' },
            ],
            position: 'Recovering from weekly demand but still below every important daily resistance',
            bull: 'Hold $520–545, form higher low and reclaim **$575–590** → **$599–610**, then **$625–635**',
            bear: 'Reject **$575–610**, or lose **$520** and fail to reclaim → **$500–490**, then **$470–450**',
            longCandidate: 'Countertrend long from **$520–545** after 4H confirmation.',
            retest: 'Reclaim above $590 may retest **$575–590**; breakdown below $520 may retest **$520–545** from underneath',
        },
        {
            ticker: 'STX', seeded: true, date: '2026-08-01',
            price: 856.41, atr: 82.13, atrPct: 9.59,
            structure: { m: 'bullish', w: 'neutral', d: 'neutral', h4: 'bearish',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend', w: 'range/correction',
                          d: 'range', h4: 'weakening beneath resistance' },
            preferred: '**Neutral — wait for resolution**',
            longSetup: 'Defend **$786–800**, reclaim $815–838 → $885',
            shortSetup: 'Reject **$885–922**, or lose $832 then $818 → $800–786',
            score: null, parts: null,
            bias: '**Neutral-to-bearish short term.** Short confirmed weakness toward the gap; long only after gap confirmation.',
            h4: 'Rally toward $900 produced a lower high and is rolling over. Price is now testing the **$842–860** moving-average cluster.',
            h4Effect: 'Short thesis improves after a 4H close below **$842**, with stronger confirmation below **$818**. Targets remain **$800–786**. Reclaiming $875–900 would delay the short.',
            demand: [
                { lo: 786, hi: 800, strength: 'fresh', note: 'gap/demand' },
                { lo: 700, hi: 700, strength: 'tested', note: 'major support' },
            ],
            supply: [
                { lo: 885, hi: 922, strength: 'tested', note: 'immediate' },
                { lo: 922, hi: 938, strength: 'fresh', note: 'breakout zone' },
                { lo: 980, hi: 1020, strength: 'fresh', note: 'potential trap' },
            ],
            position: 'Holding **$832–838** support after rejection above $900',
            bull: 'Defend **$786–800**, reclaim **$800–815**, form higher low → **$838–856**, then **$885**',
            bear: 'Reject **$885–922**, or close below **$832–838** and fail to reclaim → **$800–786**; below $786 → **$750–700**',
            longCandidate: 'Long after confirmed defense of **$786–800**.',
            retest: 'Breakdown may retest **$832–856** from underneath',
        },
        {
            ticker: 'AKAM', seeded: true, date: '2026-08-01',
            price: 115.19, atr: 5.46, atrPct: 4.74,
            structure: { m: 'neutral', w: 'bearish', d: 'bearish', h4: 'neutral',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'transition after uptrend', w: 'downtrend',
                          d: 'bearish range/bounce', h4: 'bounce stalling' },
            preferred: '**Short preferred**',
            longSetup: 'Trend changes only above **$119.22** → $124–126',
            shortSetup: 'Reject **$115–119** or lose **$107.27** → $102–104',
            score: null, parts: null,
            bias: '**Neutral-to-bearish.** Wait for resolution.',
            h4: 'Bounce is stalling beneath **$116.8–118**. MACD momentum is fading and stochastic is rolling over from overbought.',
            h4Effect: 'Keeps the **neutral-to-bearish** bias. Failure below $118 favors **$112**, then **$108**. A 4H close above $118 would open $121–124.',
            demand: [{ lo: 107.27, hi: 108.70, strength: 'weak', note: 'repeatedly tested, weakening' }],
            supply: [{ lo: 115, hi: 119.22, strength: 'tested', note: 'tested several times' }],
            position: 'Directly beneath/inside supply',
            bull: 'Close above **$119.22** → **$124–126**',
            bear: 'Loss of **$107.27** → **$102–104**, then **$98–91**',
            longCandidate: 'Long only after acceptance above **$119.22**.',
            retest: 'Breakout above $119 may retest **$115–119** as support',
        },
        {
            ticker: 'AXON', seeded: true, date: '2026-08-01',
            price: 527.64, atr: 29.02, atrPct: 5.50,
            structure: { m: 'neutral', w: 'neutral', d: 'neutral', h4: 'neutral',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'transition', w: 'recovery/transition',
                          d: 'range', h4: 'range above support' },
            preferred: '**Neutral with slight long preference**',
            longSetup: 'Break and hold **$545–550** → $580–600',
            shortSetup: 'Lose $508–515 and fail reclaim → $490–500',
            score: null, parts: null,
            bias: '**Neutral with slight bullish tilt.** Prefer confirmed breakout long.',
            h4: 'Tight balance above approximately **$508–515**, with price holding around $520–530. Momentum is neutral but stabilizing.',
            h4Effect: 'Slight bullish tilt remains. Long confirmation requires a break of **$535–545**. Loss of **$508** would shift the setup bearish toward $490–500.',
            demand: [
                { lo: 515, hi: 525, strength: 'tested', note: 'immediate' },
                { lo: 485, hi: 500, strength: 'tested', note: 'secondary' },
                { lo: 419, hi: 430, strength: 'fresh', note: 'major' },
            ],
            supply: [
                { lo: 545, hi: 565, strength: 'tested', note: 'immediate' },
                { lo: 580, hi: 600, strength: 'tested', note: 'main' },
                { lo: 625, hi: 665, strength: 'fresh', note: 'higher' },
            ],
            position: 'Holding demand but still below supply',
            bull: 'Close above **$545–550**, then hold/retest → **$580–600**, then **$625**',
            bear: 'Close below **$515** and fail to reclaim → **$490–500**, then **$466–430**',
            longCandidate: 'Breakout long above **$545–550** with a successful retest.',
            retest: 'Upside breakout may retest **$525–545** as support',
        },
        {
            ticker: 'TE', seeded: true, date: '2026-08-01',
            price: 4.11, atr: 0.19, atrPct: 4.62,
            structure: { m: 'neutral', w: 'bearish', d: 'bearish', h4: 'bearish',
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'transition/breakdown', w: 'downtrend',
                          d: 'downtrend, oversold', h4: 'bounce failing' },
            preferred: '**Short trend; long only countertrend**',
            longSetup: 'Hold $3.65–3.70 and reclaim **$4.30–4.53** → $4.72–5.34',
            shortSetup: 'Reject $4.53–4.72 or lose **$3.50** → $3.00–2.50',
            score: null, parts: null,
            bias: '**Countertrend bullish.** Long candidate from demand.',
            h4: 'The bounce from $3.55–3.70 is losing momentum. Price remains below all important 4H averages, while stochastic is rolling down.',
            h4Effect: 'The countertrend long is **not confirmed yet**. Better long trigger: hold $3.65–3.70 and reclaim **$4.30–4.53**. Below $3.55 invalidates the immediate bounce thesis.',
            demand: [
                { lo: 3.65, hi: 4.20, strength: 'tested', note: 'current demand' },
                { lo: 2.50, hi: 3.00, strength: 'fresh', note: 'lower demand' },
            ],
            supply: [
                { lo: 4.53, hi: 4.72, strength: 'tested', note: 'immediate' },
                { lo: 5.00, hi: 5.34, strength: 'tested', note: 'next' },
            ],
            position: 'Inside demand with daily RSI near 30',
            bull: 'Hold $3.65–3.70, form higher low and reclaim **$4.17** → **$4.53–4.72**, then **$5.00–5.34**',
            bear: 'Close below **$3.50–3.60** → **$3.00–2.50**',
            longCandidate: 'Countertrend long if **$3.65–3.70** holds and **$4.30–4.53** is reclaimed.',
            retest: 'Reclaim of $4.17 may retest **$4.00–4.17**',
        },
        {
            ticker: 'SMH', seeded: true, date: '2026-08-01',
            price: 540.89, atr: 27.91, atrPct: 5.16,
            structure: { m: 'bullish', w: 'bearish', d: 'bearish', h4: null,
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend', w: 'bearish correction',
                          d: 'downtrend/stretched', h4: 'not reviewed' },
            preferred: '**Short during correction**',
            longSetup: 'Hold $503–520 and reclaim **$570** → $590–605',
            shortSetup: 'Reject $557–571 or lose **$503** → $486–469',
            score: null, parts: null,
            bias: '**Neutral-to-bearish with bounce potential.** Prefer rejection short from supply.',
            demand: [
                { lo: 503, hi: 520, strength: 'tested', note: 'tested demand' },
                { lo: 469, hi: 487, strength: 'tested', note: 'secondary' },
                { lo: 419, hi: 449, strength: 'fresh', note: 'major' },
            ],
            supply: [
                { lo: 557, hi: 571, strength: 'tested', note: 'immediate' },
                { lo: 590, hi: 605, strength: 'tested', note: 'main' },
                { lo: 628, hi: 640, strength: 'fresh', note: 'top supply' },
            ],
            position: 'Holding near demand after a sharp correction',
            bull: 'Hold $503–520 and reclaim **$570** → **$590–605**; above $605 → **$628–640**',
            bear: 'Reject **$557–571** or lose **$503** → **$486–469**; below $469 → **$449–419**',
            longCandidate: 'Long if **$503–520** holds and price reclaims **$557–570**.',
            retest: 'Break below $503 may retest **$503–520** from underneath',
        },
        {
            ticker: 'INTC', seeded: true, date: '2026-08-01',
            price: 90.17, atr: 8.62, atrPct: 9.56,
            structure: { m: 'bullish', w: 'bearish', d: 'bearish', h4: null,
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend under correction', w: 'downtrend',
                          d: 'downtrend', h4: 'not reviewed' },
            preferred: '**Short preferred**',
            longSetup: 'Hold $80–84 and reclaim **$95** → $100–104',
            shortSetup: 'Reject $90–95 or lose **$80** → $75–70',
            score: null, parts: null,
            bias: '**Bearish-to-neutral.** Prefer rejection short; long only after demand confirmation.',
            demand: [
                { lo: 80, hi: 84, strength: 'tested', note: 'immediate' },
                { lo: 70, hi: 75, strength: 'tested', note: 'secondary' },
                { lo: 49, hi: 50, strength: 'fresh', note: 'major' },
            ],
            supply: [
                { lo: 90, hi: 95, strength: 'tested', note: 'immediate' },
                { lo: 100, hi: 104, strength: 'tested', note: 'main' },
                { lo: 110, hi: 115, strength: 'fresh', note: 'secondary' },
            ],
            position: 'Weak bounce attempt below resistance',
            bull: 'Defend $80–84 and reclaim **$95** → **$100–104**; above $104 → **$110–115**',
            bear: 'Reject **$90–95** or $100–104 → **$84–80**; below $80 → **$75–70**',
            longCandidate: 'Long after **$80–84** holds and price reclaims **$95**.',
            retest: 'Breakdown may retest **$80–84** from underneath',
        },
        {
            ticker: 'CIEN', seeded: true, date: '2026-08-01',
            price: 376.98, atr: 31.44, atrPct: 8.34,
            structure: { m: 'bullish', w: 'bearish', d: 'bearish', h4: null,
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend correcting', w: 'downtrend',
                          d: 'downtrend', h4: 'not reviewed' },
            preferred: '**Short preferred, but near demand**',
            longSetup: 'Hold $355–365 and reclaim **$405–420** → $445–475',
            shortSetup: 'Reject $400–420 or lose **$355** → $340–320',
            score: null, parts: null,
            bias: '**Neutral-to-bearish with bounce potential.** Long only after confirmation; otherwise reject supply.',
            demand: [
                { lo: 355, hi: 382, strength: 'tested', note: 'immediate' },
                { lo: 320, hi: 340, strength: 'fresh', note: 'stronger secondary' },
            ],
            supply: [
                { lo: 400, hi: 420, strength: 'tested', note: 'immediate' },
                { lo: 445, hi: 475, strength: 'tested', note: 'main' },
                { lo: 500, hi: 550, strength: 'fresh', note: 'higher' },
            ],
            position: 'Inside immediate demand after rejecting $400',
            bull: 'Hold **$355–365**, form higher low and reclaim **$405–420** → **$445–475**',
            bear: 'Reject **$400–420**, or close below **$355** → **$340–320**; below $320 → approximately **$300**',
            longCandidate: 'Long after **$355–365** holds and **$405–420** is reclaimed.',
            retest: 'Breakdown may retest **$355–380** from underneath',
        },
        {
            ticker: 'LLY', seeded: true, date: '2026-08-01',
            price: 1147.63, atr: 36.38, atrPct: 3.17,
            structure: { m: 'bullish', w: 'bullish', d: 'bearish', h4: null,
                         h4Note: 'read from charts' },
            // Per-frame trend, in the words it was read in. The enum above has
            // three values, so hedged wording maps to the conservative one and
            // the full phrasing is kept here.
            trendProse: { m: 'uptrend', w: 'uptrend',
                          d: 'corrective downtrend', h4: 'not reviewed' },
            preferred: '**Long preferred**',
            longSetup: 'Hold $1,119–1,130 and reclaim **$1,175** → $1,200–1,250',
            shortSetup: 'Short only after loss and failed reclaim of **$1,119** → $1,050',
            score: null, parts: null,
            bias: '**Neutral-to-bullish.** Prefer confirmed long from demand.',
            demand: [
                { lo: 1119, hi: 1130, strength: 'tested', note: 'immediate' },
                { lo: 1040, hi: 1060, strength: 'tested', note: 'secondary' },
                { lo: 1000, hi: 1020, strength: 'fresh', note: 'major' },
            ],
            supply: [
                { lo: 1175, hi: 1200, strength: 'tested', note: 'immediate' },
                { lo: 1230, hi: 1250, strength: 'fresh', note: 'major' },
            ],
            position: 'Testing daily demand and 50-day area',
            bull: 'Hold $1,119–1,130 and reclaim **$1,175–1,180** → **$1,200**, then **$1,230–1,250**',
            bear: 'Close below **$1,119** and fail to reclaim → **$1,050**, then **$1,000–1,020**',
            longCandidate: 'Long from **$1,119–1,130** demand after a higher low and reclaim of **$1,175**.',
            retest: 'Reclaim may retest **$1,150–1,175** as support',
        },
    ],
};
