// ── App config ──────────────────────────────────────────────────────────────
const APP_CONFIG = {
  // Year shown in the heatmap calendar
  heatmapYear: 2026,
  // Color thresholds for daily P&L heatmap squares (% from entry)
  pnlBuckets: [
    { min:  8, cls: 'hm-gain-3' },
    { min:  3, cls: 'hm-gain-2' },
    { min:  0, cls: 'hm-gain-1' },
    { min: -3, cls: 'hm-loss-1' },
    { min: -8, cls: 'hm-loss-2' },
    { min: -Infinity, cls: 'hm-loss-3' },
  ],
};

// ── Ticker alerts ───────────────────────────────────────────────────────────
const TICKER_DATA = [
  { tier: 'warning',        icon: '⚠', symbol: 'TSEM',  body: 'Long · enter at <strong>$200.75</strong> · stop <strong>$179.00</strong> · target <strong>$250.00</strong> · wide stop — go small!' },
  { tier: 'high-potential', icon: '↗', symbol: 'STX',   body: 'Short · current <strong>$645.82</strong> · target <strong>$361.00</strong> · <strong>44.1%</strong> potential' },
  { tier: 'high-potential', icon: '↗', symbol: 'BE',    body: 'Short · current <strong>$279.48</strong> · target <strong>$185.00</strong> · <strong>33.8%</strong> potential' },
  { tier: 'high-potential', icon: '↗', symbol: 'AMD',   body: 'Short · current <strong>$351.50</strong> · target <strong>$285.00</strong> · <strong>18.9%</strong> potential' },
  { tier: 'setup',          icon: '↗', symbol: 'NBIS',  body: 'Earnings today · watch for push up to re-enter Short' },
  { tier: 'setup',          icon: '↗', symbol: 'GOOGL', body: 'Short · current <strong>$383.60</strong> · large position · <strong>-9.3%</strong> · watching' },
];

// ── Trade setups ────────────────────────────────────────────────────────────
// Each setup describes a planned trade. Trigger detection, daily P&L, and
// "if held to today" P&L are all computed from prices.js historical OHLC.
//
// Fields:
//   id              unique slug
//   symbol          ticker
//   direction       'Long' | 'Short'
//   entryTrigger    price that, once hit, triggers entry (null = not set)
//   stop            protective stop price (null = none yet)
//   target          profit target price (null = none yet)
//   setupType       'Breakout' | 'Pullback' | 'Reversal' | 'Earnings' | …
//   tier            null | 'warning' | 'high-potential' | 'setup'
//   addedDate       ISO date when the setup was added (YYYY-MM-DD)
//   notes           freeform text
//   status          'watching' | 'cancelled' | 'closed'
//                   (a 'watching' setup whose entry was hit becomes 'open'
//                    automatically — set 'closed' only after the manual exit)
//   triggeredDate   manual override (YYYY-MM-DD) or null = auto-detect
//   closedDate      ISO date the trade was manually closed (null = still open)
//   closePrice      closing price (null = use that day's close)
//   closeReason     'target' | 'stop' | 'manual' | 'time' | null
const SETUPS = [
  {
    id: 'tsem-2026-04-30', symbol: 'TSEM', direction: 'Long',
    entryTrigger: 200.75, stop: 179.00, target: 250.00,
    setupType: 'Breakout', tier: 'warning',
    addedDate: '2026-04-30',
    notes: 'Top-rated semicon play out of Israel · should get a boost from QCOM earnings and is set to break the recent pullback · wide stop — go small!',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'stx-2026-04-16', symbol: 'STX', direction: 'Short',
    entryTrigger: 553.79, stop: null, target: 361.00,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-04-16',
    notes: 'Extended after blow-off · 44% target · sized for slow grind down',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'be-2026-04-21', symbol: 'BE', direction: 'Short',
    entryTrigger: 253.03, stop: null, target: 185.00,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-04-21',
    notes: 'Parabolic · 33.8% potential to mean',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'amd-2026-04-23', symbol: 'AMD', direction: 'Short',
    entryTrigger: 309.14, stop: null, target: 285.00,
    setupType: 'Pullback', tier: 'high-potential',
    addedDate: '2026-04-23',
    notes: 'Short the rip back into resistance',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nbis-2026-04-30', symbol: 'NBIS', direction: 'Short',
    entryTrigger: null, stop: null, target: null,
    setupType: 'Earnings', tier: 'setup',
    addedDate: '2026-04-30',
    notes: 'Earnings today · watch for a push up to re-enter Short',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'googl-2026-04-14', symbol: 'GOOGL', direction: 'Short',
    entryTrigger: 351.00, stop: null, target: null,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-04-14',
    notes: 'Large position planned · watching for confirmation',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'mu-2026-04-24', symbol: 'MU', direction: 'Short',
    entryTrigger: 518.25, stop: null, target: null,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-04-24',
    notes: 'Mean-reversion short',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'figs-2026-04-22', symbol: 'FIGS', direction: 'Long',
    entryTrigger: 15.71, stop: 14.50, target: 20.00,
    setupType: 'Breakout', tier: null,
    addedDate: '2026-04-22',
    notes: 'Tight base · 27% to target · small risk',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nxt-2026-04-24', symbol: 'NXT', direction: 'Long',
    entryTrigger: 124.70, stop: 113.50, target: 160.00,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-04-24',
    notes: 'Solar leader · bid back to 50dma',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  // ── May 1 setups ─────────────────────────────────────────────────────────
  {
    id: 'googl-swing-2026-05-01', symbol: 'GOOGL', direction: 'Short',
    entryTrigger: 390.00, stop: null, target: null,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-05-01',
    notes: 'Hidden upswing trend line retest zone $388.36–$390.00 · day trade or swing short entry at upper end of zone · zone touched May 5 (H=392.82) but price continued to $400 — watch for reversal',
    status: 'watching', triggeredDate: '2026-05-05', closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'team-short-2026-05-01', symbol: 'TEAM', direction: 'Short',
    entryTrigger: 92.93, stop: null, target: null,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-01',
    notes: 'Bouncing from deep lows ($55.91), currently drawing down · short into resistance at $92.93 · resistance hit May 4 (H=96.32)',
    status: 'watching', triggeredDate: '2026-05-04', closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'team-long-2026-05-01', symbol: 'TEAM', direction: 'Long',
    entryTrigger: 75.00, stop: null, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-01',
    notes: 'Pierce of $75.00 expected to bring buyers in · bouncing from deep lows ($55.91)',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nvda-2026-05-01', symbol: 'NVDA', direction: 'Long',
    entryTrigger: 195.55, stop: null, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-01',
    notes: 'Sharp sell-off · support zone $194.37–$195.55 (gap fill) · long on pierce into zone · dipped to 194.74 on May 4, then rallied to $211',
    status: 'watching', triggeredDate: '2026-05-04', closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'amzn-2026-05-01', symbol: 'AMZN', direction: 'Short',
    entryTrigger: 258.74, stop: 275.00, target: 238.10,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-01',
    notes: 'Negative RSI divergence at top of parallel channel · break below $258.74 targets midline $238.10 · psych resistance $275 / $300',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'msft-short-2026-05-01', symbol: 'MSFT', direction: 'Short',
    entryTrigger: 424.06, stop: 433.12, target: 393.11,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-01',
    notes: 'Day trade short level · stop above bull line-in-sand $433.12 · support target $393.11 · level reached May 7 (H=427.98)',
    status: 'watching', triggeredDate: '2026-05-07', closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'msft-long-2026-05-01', symbol: 'MSFT', direction: 'Long',
    entryTrigger: 433.12, stop: 393.11, target: 438.37,
    setupType: 'Breakout', tier: null,
    addedDate: '2026-05-01',
    notes: 'Buyers recaptured downswing trend line · bull line-in-sand $433.12 · next resistance $438.37 · support $393.11',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'intc-short-2026-05-01', symbol: 'INTC', direction: 'Short',
    entryTrigger: 100.00, stop: null, target: 87.53,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-01',
    notes: 'RSI 87.56 — severely overextended · rejected at $100 psych level · targets $87.53 → $67.95 → $54.37 on major pullback · CANCELLED: price broke out above $100 on May 5',
    status: 'cancelled', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'intc-long-2026-05-01', symbol: 'INTC', direction: 'Long',
    entryTrigger: 100.00, stop: null, target: 110.00,
    setupType: 'Breakout', tier: null,
    addedDate: '2026-05-01',
    notes: 'Breakout above $100 psych level targets $110 · only valid on confirmed close above $100 · broke out May 5, hit target same day',
    status: 'closed',
    triggeredDate: '2026-05-05',
    closedDate: '2026-05-05',
    closePrice: 110.00,
    closeReason: 'target',
  },
  // ── 2026-05-05 batch ─────────────────────────────────────────────────────
  {
    id: 'googl-2026-05-05', symbol: 'GOOGL', direction: 'Short',
    entryTrigger: 390.10, stop: null, target: null,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-05-05',
    notes: 'Cleared all-time highs and broke below upswing trend line · swing short entry $390.10 · close above → next resistance $400 · DCA every $40 (10%) higher',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nvda-2026-05-05', symbol: 'NVDA', direction: 'Long',
    entryTrigger: 195.56, stop: 189.31, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-05',
    notes: 'Selling off toward long entry levels · day-trade pierce of $195.56 (target $194.92–$194.21) · conservative gap fill $189.31',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'sndk-2026-05-05', symbol: 'SNDK', direction: 'Short',
    entryTrigger: 1454.00, stop: null, target: null,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-05-05',
    notes: 'SanDisk · overextended on log chart · shortable swing target $1,454 · DCA short every $100 higher',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'mu-2026-05-05', symbol: 'MU', direction: 'Short',
    entryTrigger: 600.00, stop: null, target: null,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-05-05',
    notes: 'Massive overextension (up 93% since 2026-03-31) · swing short pierce of $600 (aggressive $595) · day-trade short any level above $590',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'chrw-2026-05-05', symbol: 'CHRW', direction: 'Long',
    entryTrigger: 159.96, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-05',
    notes: 'Drawing down · aggressive day-trade long $159.96 · 15-min close below → re-enter at $150 pierce or gap $148.44',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'ups-2026-05-05', symbol: 'UPS', direction: 'Long',
    entryTrigger: 97.51, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-05',
    notes: 'Hitting a gap in the charts · aggressive long $97.51 · conservative pierce $95.00 · deeper gap $84.93',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'fdx-2026-05-05', symbol: 'FDX', direction: 'Long',
    entryTrigger: 357.00, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-05',
    notes: 'Following UPS lower after breaking upswing trend line · long at $357 round number · 15-min close below → next long $341.81 · swing short alt on retrace to $386.23',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  // ── 2026-05-06 batch ─────────────────────────────────────────────────────
  {
    id: 'lulu-scalp-2026-05-06', symbol: 'LULU', direction: 'Long',
    entryTrigger: 923.20, stop: 900.00, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-06',
    notes: 'Quick-scalp long at gap fill $923.20 · psychological support at $900 · separate from swing level at $815.75',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'tmdx-2026-05-06', symbol: 'TMDX', direction: 'Long',
    entryTrigger: 68.58, stop: null, target: null,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Pre-market drop to $68.58 = aggressive long · conservative gap fill $64.19 · DCA down toward low pivots',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nice-2026-05-06', symbol: 'NICE', direction: 'Long',
    entryTrigger: 97.00, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Aggressive long at prior gap fill $97.00 · conservative entry on pierce of $94.65 for technical bounce',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'cpng-2026-05-06', symbol: 'CPNG', direction: 'Long',
    entryTrigger: 17.43, stop: 16.79, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Long at gap fill $17.43 · if it consolidates into a bear flag there, next support $16.79',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'anet-2026-05-06', symbol: 'ANET', direction: 'Long',
    entryTrigger: 141.18, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Aggressive long at $141.18 · more significant support $138.78 · ultra-conservative gap fill $133.70',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'ups-2026-05-06', symbol: 'UPS', direction: 'Long',
    entryTrigger: 25.58, stop: null, target: 31.40,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Caught bid at gap fill, hit $30 · conservative long entry now $25.58 · resistance $31.40 then $35.36',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'shop-2026-05-06', symbol: 'SHOP', direction: 'Long',
    entryTrigger: 104.90, stop: 100.05, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Aggressive long at $104.90 · 15-min close fail → support $100.05–$101.35 · deeper long-term support $91.77',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'pltr-2026-05-06', symbol: 'PLTR', direction: 'Long',
    entryTrigger: 12.86, stop: 122.67, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Long entries $12.86 and swing $12.55 · daily close below $122.67 = stop-out',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'intc-2026-05-06', symbol: 'INTC', direction: 'Short',
    entryTrigger: 111.00, stop: 112.00, target: 88.00,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-05-06',
    notes: 'Resistance $111–$112 · up 176% from lows, overextended · pullback target $88, long-term $54.73',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'amd-long-2026-05-06', symbol: 'AMD', direction: 'Long',
    entryTrigger: 426.47, stop: null, target: 444.50,
    setupType: 'Breakout', tier: 'setup',
    addedDate: '2026-05-06',
    notes: 'Resistance at $426.47 post-earnings caused 5% pullback · if bullish momentum continues, breaks trend lines to $444.50, possibly $500.00',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  // ── 2026-05-07 batch ─────────────────────────────────────────────────────
  {
    id: 'ddog-2026-05-07', symbol: 'DDOG', direction: 'Short',
    entryTrigger: 202.00, stop: 210.00, target: 175.20,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-05-07',
    notes: 'Earnings rip · triple-top resistance at $202 · short into the level · target support $175.20, then $161.24',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'ftnt-2026-05-07', symbol: 'FTNT', direction: 'Short',
    entryTrigger: 114.82, stop: 118.50, target: 100.00,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Earnings ripped 32% · pierced double-top at $114.82 then retreated · target psychological $100, gap fill $90',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'mdb-2026-05-07', symbol: 'MDB', direction: 'Long',
    entryTrigger: 302.90, stop: 279.83, target: null,
    setupType: 'Breakout', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Gapped up out of bearish consolidation · tagged resistance $302.90 and retreated · need hold above $279.83 to keep momentum',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'axon-2026-05-07', symbol: 'AXON', direction: 'Long',
    entryTrigger: null, stop: 414.53, target: 471.00,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Up 10% post-earnings · V-shaped recovery · roadmap to $471 then $493.12 if it holds $414.53',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'googl-2026-05-07', symbol: 'GOOGL', direction: 'Long',
    entryTrigger: 381.00, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Vying with NVDA for top market cap · overbought · expecting retrace to top of parallel channel ~$381 for buy',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nvda-2026-05-07', symbol: 'NVDA', direction: 'Long',
    entryTrigger: 217.37, stop: null, target: null,
    setupType: 'Breakout', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Bounced off long-term trend line · double-layer barrier at $216.50 / $217.37 · clear both to regain bullish parallel',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'nvda-short-2026-05-07', symbol: 'NVDA', direction: 'Short',
    entryTrigger: 212.00, stop: null, target: null,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-07',
    notes: 'Day-trade short · previous double top around $212',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'net-2026-05-07', symbol: 'NET', direction: 'Long',
    entryTrigger: 205.00, stop: 198.00, target: 220.00,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Sold off post-earnings despite sector strength · near-term support $220 · buy gap fill at $205, psychological $200',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'crwv-2026-05-07', symbol: 'CRWV', direction: 'Short',
    entryTrigger: 15.30, stop: null, target: null,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-07',
    notes: 'CoreWeave · flat AH after post-earnings pop · overbought · resistance $14.31 / $15.30',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'coin-2026-05-07', symbol: 'COIN', direction: 'Long',
    entryTrigger: 174.53, stop: 148.45, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Dropped to $184 after earnings · approaching cliff · gap-fill supports $174.53 then $161 · long-term support $148.45',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'shak-2026-05-07', symbol: 'SHAK', direction: 'Long',
    entryTrigger: 67.47, stop: 64.16, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Broke below pre-market low · filled gap at $67.47 = good long entry · conservative range $66.05–$66.69 · max downside $64.16',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'vitl-2026-05-07', symbol: 'VITL', direction: 'Long',
    entryTrigger: 7.85, stop: null, target: 12.00,
    setupType: 'Reversal', tier: 'high-potential',
    addedDate: '2026-05-07',
    notes: 'Huge pre-market sell-off to $7.85 then bounced 18% · day & swing buyer at $7.85 · target $12.00 (~52% move)',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'pltr-2026-05-07', symbol: 'PLTR', direction: 'Long',
    entryTrigger: 12.86, stop: null, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-07',
    notes: 'Downside target for long entry $12.86 · swing trade level $12.55 · need to clear & confirm above downward trend line off recent pivot tops to turn bullish',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'mu-reshort-2026-05-07', symbol: 'MU', direction: 'Short',
    entryTrigger: 671.56, stop: 683.12, target: 660.00,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-07',
    notes: 'Topping tail on 10-min at $683.12 led to $20 drop to $660 · re-short at 50%/61.8% fib retrace ($671.56 / $674.29)',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'anet-2026-05-07', symbol: 'ANET', direction: 'Long',
    entryTrigger: 133.70, stop: null, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-07',
    notes: 'Hit $141.18 multiple times · expected to break lower · next major long entry $133.70',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'intc-2026-05-07', symbol: 'INTC', direction: 'Short',
    entryTrigger: null, stop: null, target: null,
    setupType: 'Reversal', tier: null,
    addedDate: '2026-05-07',
    notes: 'Negative RSI divergence — buying pressure weakening despite higher prices · resistance at daily upward trend line · rollover expected',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'shop-2026-05-07', symbol: 'SHOP', direction: 'Short',
    entryTrigger: 104.90, stop: null, target: 91.77,
    setupType: 'Reversal', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Bounced off $104.90 and pushing higher · short on return to $104.90 · breakdown target $91.77',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'bros-2026-05-07', symbol: 'BROS', direction: 'Long',
    entryTrigger: 50.60, stop: 48.40, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Long entry at $50.60 · stop on 15-min close below — do not average down · next gap support $48.40',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'arm-2026-05-07', symbol: 'ARM', direction: 'Long',
    entryTrigger: 228.84, stop: 187.34, target: null,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-05-07',
    notes: 'First long level at gap fill $228.84 · day-trade only (high end of chart) · secondary support $187.34',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'lulu-2026-05-07', symbol: 'LULU', direction: 'Long',
    entryTrigger: 815.75, stop: 791.37, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Bounce at $92.32 broke lower · major support at upward trend line $815.75 · daily close below $791.37 = stop-out',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'avav-2026-05-07', symbol: 'AVAV', direction: 'Long',
    entryTrigger: 150.19, stop: null, target: 169.07,
    setupType: 'Breakout', tier: 'high-potential',
    addedDate: '2026-05-07',
    notes: 'Consolidating near support · pierce of $150 ($150.19) for day & swing entry · resistance target $169.07',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  {
    id: 'qcom-2026-05-07', symbol: 'QCOM', direction: 'Long',
    entryTrigger: 209.64, stop: null, target: null,
    setupType: 'Pullback', tier: 'setup',
    addedDate: '2026-05-07',
    notes: 'Aggressive long at gap fill $209.64 · conservative alt is short higher up at $212.53 gap fill',
    status: 'watching', triggeredDate: null, closedDate: null, closePrice: null, closeReason: null,
  },
  // Example of an already-triggered setup that was manually closed —
  // delete or replace once you have your own real history.
  {
    id: 'nbis-closed-2026-04-30', symbol: 'NBIS', direction: 'Long',
    entryTrigger: 86.50, stop: 80.00, target: 105.00,
    setupType: 'Pullback', tier: null,
    addedDate: '2026-04-25',
    notes: 'Closed for +15.7% the day before earnings',
    status: 'closed',
    triggeredDate: '2026-04-25',
    closedDate: '2026-04-30',
    closePrice: 100.10,
    closeReason: 'target',
  },
];
