#!/usr/bin/env python3
"""
fetch_setups.py — pulls daily OHLC history for every symbol in data.js
and writes prices.js, a small JS module the web app reads.

Workflow:
    source .venv/bin/activate
    python3 fetch_setups.py

The script reads SETUPS from data.js (it just regex-greps the symbols and
addedDate fields — no JS engine needed) and fetches each symbol from its
addedDate through today, plus a small lookback so the heatmap shows a few
extra context days.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

try:
    import yfinance as yf
except ImportError:
    sys.exit("yfinance is required.  Run:  pip install -r requirements.txt")


REPO = Path(__file__).resolve().parent
DATA_JS = REPO / "data.js"
PRICES_JS = REPO / "prices.js"

# Lookback before each setup's addedDate, so the heatmap shows a little
# context before the setup was placed.
LOOKBACK_DAYS = 14


def parse_setups(text: str) -> list[dict]:
    """Pull (symbol, addedDate) pairs out of data.js by regex."""
    rows = re.findall(
        r"symbol:\s*'([A-Z.\-]+)'.*?addedDate:\s*'(\d{4}-\d{2}-\d{2})'",
        text,
        re.DOTALL,
    )
    return [{"symbol": s, "added": a} for s, a in rows]


def earliest_per_symbol(rows: list[dict]) -> dict[str, str]:
    out: dict[str, str] = {}
    for r in rows:
        sym, added = r["symbol"], r["added"]
        if sym not in out or added < out[sym]:
            out[sym] = added
    return out


def fetch_ohlc(symbol: str, start: str) -> list[dict]:
    start_dt = datetime.fromisoformat(start) - timedelta(days=LOOKBACK_DAYS)
    end_dt = date.today() + timedelta(days=1)
    df = yf.Ticker(symbol).history(
        start=start_dt.strftime("%Y-%m-%d"),
        end=end_dt.strftime("%Y-%m-%d"),
        auto_adjust=False,
    )
    bars: list[dict] = []
    for ts, row in df.iterrows():
        bars.append({
            "d": ts.strftime("%Y-%m-%d"),
            "o": round(float(row["Open"]), 4),
            "h": round(float(row["High"]), 4),
            "l": round(float(row["Low"]), 4),
            "c": round(float(row["Close"]), 4),
        })
    return bars


def main() -> int:
    if not DATA_JS.exists():
        sys.exit(f"data.js not found at {DATA_JS}")

    rows = parse_setups(DATA_JS.read_text())
    if not rows:
        sys.exit("No setups parsed from data.js")
    starts = earliest_per_symbol(rows)
    print(f"Fetching {len(starts)} symbols…")

    prices: dict[str, list[dict]] = {}
    for sym, start in sorted(starts.items()):
        try:
            bars = fetch_ohlc(sym, start)
            prices[sym] = bars
            print(f"  {sym:<8} {len(bars):>4} bars from {start}")
        except Exception as e:
            print(f"  {sym:<8} ERROR ({e})")
            prices[sym] = []

    # Write a JS module so it can be loaded with a plain <script> tag —
    # no fetch / CORS gymnastics needed in the browser.
    body = json.dumps(prices, separators=(",", ":"))
    out = (
        "// AUTO-GENERATED by fetch_setups.py — do not edit by hand.\n"
        f"// Generated {datetime.now().isoformat(timespec='seconds')}\n"
        f"const PRICES = {body};\n"
    )
    PRICES_JS.write_text(out)
    print(f"\nWrote {PRICES_JS.relative_to(REPO)} ({PRICES_JS.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
