// AUTO-GENERATED by fetch_setups.py — do not edit by hand.
// Run `python3 fetch_setups.py` to regenerate.
//
// Until you run the script, this stub keeps the app from erroring out:
// every setup will show as "watching, no data" because PRICES is empty.
const PRICES = {};
